; Licensed to the Apache Software Foundation (ASF) under one
; or more contributor license agreements.  See the NOTICE file
; distributed with this work for additional information
; regarding copyright ownership.  The ASF licenses this file
; to you under the Apache License, Version 2.0 (the
; "License"); you may not use this file except in compliance
; with the License.  You may obtain a copy of the License at
;
;   http://www.apache.org/licenses/LICENSE-2.0
;
; Unless required by applicable law or agreed to in writing,
; software distributed under the License is distributed on an
; "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
; KIND, either express or implied.  See the License for the
; specific language governing permissions and limitations
; under the License.
;    Licensed to the Apache Software Foundation (ASF) under one or more
;    contributor license agreements.  See the NOTICE file distributed with

.class public org/apache/harmony/test/stress/classloader/share/FieldsLmtClasses/testFieldsLmt_C1
.super java/lang/Object
.implements org/apache/harmony/test/stress/classloader/share/FieldsLmtClasses/testFieldsLmt_C

.field protected testF0 I
.field protected testF1 I
.field protected testF2 I
.field protected testF3 I
.field protected testF4 I
.field protected testF5 I
.field protected testF6 I
.field protected testF7 I
.field protected testF8 I
.field protected testF9 I
.field protected testF10 I
.field protected testF11 I
.field protected testF12 I
.field protected testF13 I
.field protected testF14 I
.field protected testF15 I
.field protected testF16 I
.field protected testF17 I
.field protected testF18 I
.field protected testF19 I
.field protected testF20 I
.field protected testF21 I
.field protected testF22 I
.field protected testF23 I
.field protected testF24 I
.field protected testF25 I
.field protected testF26 I
.field protected testF27 I
.field protected testF28 I
.field protected testF29 I
.field protected testF30 I
.field protected testF31 I
.field protected testF32 I
.field protected testF33 I
.field protected testF34 I
.field protected testF35 I
.field protected testF36 I
.field protected testF37 I
.field protected testF38 I
.field protected testF39 I
.field protected testF40 I
.field protected testF41 I
.field protected testF42 I
.field protected testF43 I
.field protected testF44 I
.field protected testF45 I
.field protected testF46 I
.field protected testF47 I
.field protected testF48 I
.field protected testF49 I
.field protected testF50 I
.field protected testF51 I
.field protected testF52 I
.field protected testF53 I
.field protected testF54 I
.field protected testF55 I
.field protected testF56 I
.field protected testF57 I
.field protected testF58 I
.field protected testF59 I
.field protected testF60 I
.field protected testF61 I
.field protected testF62 I
.field protected testF63 I
.field protected testF64 I
.field protected testF65 I
.field protected testF66 I
.field protected testF67 I
.field protected testF68 I
.field protected testF69 I
.field protected testF70 I
.field protected testF71 I
.field protected testF72 I
.field protected testF73 I
.field protected testF74 I
.field protected testF75 I
.field protected testF76 I
.field protected testF77 I
.field protected testF78 I
.field protected testF79 I
.field protected testF80 I
.field protected testF81 I
.field protected testF82 I
.field protected testF83 I
.field protected testF84 I
.field protected testF85 I
.field protected testF86 I
.field protected testF87 I
.field protected testF88 I
.field protected testF89 I
.field protected testF90 I
.field protected testF91 I
.field protected testF92 I
.field protected testF93 I
.field protected testF94 I
.field protected testF95 I
.field protected testF96 I
.field protected testF97 I
.field protected testF98 I
.field protected testF99 I
.field protected testF100 I
.field protected testF101 I
.field protected testF102 I
.field protected testF103 I
.field protected testF104 I
.field protected testF105 I
.field protected testF106 I
.field protected testF107 I
.field protected testF108 I
.field protected testF109 I
.field protected testF110 I
.field protected testF111 I
.field protected testF112 I
.field protected testF113 I
.field protected testF114 I
.field protected testF115 I
.field protected testF116 I
.field protected testF117 I
.field protected testF118 I
.field protected testF119 I
.field protected testF120 I
.field protected testF121 I
.field protected testF122 I
.field protected testF123 I
.field protected testF124 I
.field protected testF125 I
.field protected testF126 I
.field protected testF127 I
.field protected testF128 I
.field protected testF129 I
.field protected testF130 I
.field protected testF131 I
.field protected testF132 I
.field protected testF133 I
.field protected testF134 I
.field protected testF135 I
.field protected testF136 I
.field protected testF137 I
.field protected testF138 I
.field protected testF139 I
.field protected testF140 I
.field protected testF141 I
.field protected testF142 I
.field protected testF143 I
.field protected testF144 I
.field protected testF145 I
.field protected testF146 I
.field protected testF147 I
.field protected testF148 I
.field protected testF149 I
.field protected testF150 I
.field protected testF151 I
.field protected testF152 I
.field protected testF153 I
.field protected testF154 I
.field protected testF155 I
.field protected testF156 I
.field protected testF157 I
.field protected testF158 I
.field protected testF159 I
.field protected testF160 I
.field protected testF161 I
.field protected testF162 I
.field protected testF163 I
.field protected testF164 I
.field protected testF165 I
.field protected testF166 I
.field protected testF167 I
.field protected testF168 I
.field protected testF169 I
.field protected testF170 I
.field protected testF171 I
.field protected testF172 I
.field protected testF173 I
.field protected testF174 I
.field protected testF175 I
.field protected testF176 I
.field protected testF177 I
.field protected testF178 I
.field protected testF179 I
.field protected testF180 I
.field protected testF181 I
.field protected testF182 I
.field protected testF183 I
.field protected testF184 I
.field protected testF185 I
.field protected testF186 I
.field protected testF187 I
.field protected testF188 I
.field protected testF189 I
.field protected testF190 I
.field protected testF191 I
.field protected testF192 I
.field protected testF193 I
.field protected testF194 I
.field protected testF195 I
.field protected testF196 I
.field protected testF197 I
.field protected testF198 I
.field protected testF199 I
.field protected testF200 I
.field protected testF201 I
.field protected testF202 I
.field protected testF203 I
.field protected testF204 I
.field protected testF205 I
.field protected testF206 I
.field protected testF207 I
.field protected testF208 I
.field protected testF209 I
.field protected testF210 I
.field protected testF211 I
.field protected testF212 I
.field protected testF213 I
.field protected testF214 I
.field protected testF215 I
.field protected testF216 I
.field protected testF217 I
.field protected testF218 I
.field protected testF219 I
.field protected testF220 I
.field protected testF221 I
.field protected testF222 I
.field protected testF223 I
.field protected testF224 I
.field protected testF225 I
.field protected testF226 I
.field protected testF227 I
.field protected testF228 I
.field protected testF229 I
.field protected testF230 I
.field protected testF231 I
.field protected testF232 I
.field protected testF233 I
.field protected testF234 I
.field protected testF235 I
.field protected testF236 I
.field protected testF237 I
.field protected testF238 I
.field protected testF239 I
.field protected testF240 I
.field protected testF241 I
.field protected testF242 I
.field protected testF243 I
.field protected testF244 I
.field protected testF245 I
.field protected testF246 I
.field protected testF247 I
.field protected testF248 I
.field protected testF249 I
.field protected testF250 I
.field protected testF251 I
.field protected testF252 I
.field protected testF253 I
.field protected testF254 I
.field protected testF255 I
.field protected testF256 I
.field protected testF257 I
.field protected testF258 I
.field protected testF259 I
.field protected testF260 I
.field protected testF261 I
.field protected testF262 I
.field protected testF263 I
.field protected testF264 I
.field protected testF265 I
.field protected testF266 I
.field protected testF267 I
.field protected testF268 I
.field protected testF269 I
.field protected testF270 I
.field protected testF271 I
.field protected testF272 I
.field protected testF273 I
.field protected testF274 I
.field protected testF275 I
.field protected testF276 I
.field protected testF277 I
.field protected testF278 I
.field protected testF279 I
.field protected testF280 I
.field protected testF281 I
.field protected testF282 I
.field protected testF283 I
.field protected testF284 I
.field protected testF285 I
.field protected testF286 I
.field protected testF287 I
.field protected testF288 I
.field protected testF289 I
.field protected testF290 I
.field protected testF291 I
.field protected testF292 I
.field protected testF293 I
.field protected testF294 I
.field protected testF295 I
.field protected testF296 I
.field protected testF297 I
.field protected testF298 I
.field protected testF299 I
.field protected testF300 I
.field protected testF301 I
.field protected testF302 I
.field protected testF303 I
.field protected testF304 I
.field protected testF305 I
.field protected testF306 I
.field protected testF307 I
.field protected testF308 I
.field protected testF309 I
.field protected testF310 I
.field protected testF311 I
.field protected testF312 I
.field protected testF313 I
.field protected testF314 I
.field protected testF315 I
.field protected testF316 I
.field protected testF317 I
.field protected testF318 I
.field protected testF319 I
.field protected testF320 I
.field protected testF321 I
.field protected testF322 I
.field protected testF323 I
.field protected testF324 I
.field protected testF325 I
.field protected testF326 I
.field protected testF327 I
.field protected testF328 I
.field protected testF329 I
.field protected testF330 I
.field protected testF331 I
.field protected testF332 I
.field protected testF333 I
.field protected testF334 I
.field protected testF335 I
.field protected testF336 I
.field protected testF337 I
.field protected testF338 I
.field protected testF339 I
.field protected testF340 I
.field protected testF341 I
.field protected testF342 I
.field protected testF343 I
.field protected testF344 I
.field protected testF345 I
.field protected testF346 I
.field protected testF347 I
.field protected testF348 I
.field protected testF349 I
.field protected testF350 I
.field protected testF351 I
.field protected testF352 I
.field protected testF353 I
.field protected testF354 I
.field protected testF355 I
.field protected testF356 I
.field protected testF357 I
.field protected testF358 I
.field protected testF359 I
.field protected testF360 I
.field protected testF361 I
.field protected testF362 I
.field protected testF363 I
.field protected testF364 I
.field protected testF365 I
.field protected testF366 I
.field protected testF367 I
.field protected testF368 I
.field protected testF369 I
.field protected testF370 I
.field protected testF371 I
.field protected testF372 I
.field protected testF373 I
.field protected testF374 I
.field protected testF375 I
.field protected testF376 I
.field protected testF377 I
.field protected testF378 I
.field protected testF379 I
.field protected testF380 I
.field protected testF381 I
.field protected testF382 I
.field protected testF383 I
.field protected testF384 I
.field protected testF385 I
.field protected testF386 I
.field protected testF387 I
.field protected testF388 I
.field protected testF389 I
.field protected testF390 I
.field protected testF391 I
.field protected testF392 I
.field protected testF393 I
.field protected testF394 I
.field protected testF395 I
.field protected testF396 I
.field protected testF397 I
.field protected testF398 I
.field protected testF399 I
.field protected testF400 I
.field protected testF401 I
.field protected testF402 I
.field protected testF403 I
.field protected testF404 I
.field protected testF405 I
.field protected testF406 I
.field protected testF407 I
.field protected testF408 I
.field protected testF409 I
.field protected testF410 I
.field protected testF411 I
.field protected testF412 I
.field protected testF413 I
.field protected testF414 I
.field protected testF415 I
.field protected testF416 I
.field protected testF417 I
.field protected testF418 I
.field protected testF419 I
.field protected testF420 I
.field protected testF421 I
.field protected testF422 I
.field protected testF423 I
.field protected testF424 I
.field protected testF425 I
.field protected testF426 I
.field protected testF427 I
.field protected testF428 I
.field protected testF429 I
.field protected testF430 I
.field protected testF431 I
.field protected testF432 I
.field protected testF433 I
.field protected testF434 I
.field protected testF435 I
.field protected testF436 I
.field protected testF437 I
.field protected testF438 I
.field protected testF439 I
.field protected testF440 I
.field protected testF441 I
.field protected testF442 I
.field protected testF443 I
.field protected testF444 I
.field protected testF445 I
.field protected testF446 I
.field protected testF447 I
.field protected testF448 I
.field protected testF449 I
.field protected testF450 I
.field protected testF451 I
.field protected testF452 I
.field protected testF453 I
.field protected testF454 I
.field protected testF455 I
.field protected testF456 I
.field protected testF457 I
.field protected testF458 I
.field protected testF459 I
.field protected testF460 I
.field protected testF461 I
.field protected testF462 I
.field protected testF463 I
.field protected testF464 I
.field protected testF465 I
.field protected testF466 I
.field protected testF467 I
.field protected testF468 I
.field protected testF469 I
.field protected testF470 I
.field protected testF471 I
.field protected testF472 I
.field protected testF473 I
.field protected testF474 I
.field protected testF475 I
.field protected testF476 I
.field protected testF477 I
.field protected testF478 I
.field protected testF479 I
.field protected testF480 I
.field protected testF481 I
.field protected testF482 I
.field protected testF483 I
.field protected testF484 I
.field protected testF485 I
.field protected testF486 I
.field protected testF487 I
.field protected testF488 I
.field protected testF489 I
.field protected testF490 I
.field protected testF491 I
.field protected testF492 I
.field protected testF493 I
.field protected testF494 I
.field protected testF495 I
.field protected testF496 I
.field protected testF497 I
.field protected testF498 I
.field protected testF499 I

.field protected testF9999 I
;
; standard initializer
.method public <init>()V
   aload_0
   invokenonvirtual java/lang/Object/<init>()V
   return
.end method
.method public put()V
    .limit stack 2
    .limit locals 2
    aload_0
    sipush 333
    putfield  org/apache/harmony/test/stress/classloader/share/FieldsLmtClasses/testFieldsLmt_C1/testF0 I
    aload_0
    sipush 555
    putfield  org/apache/harmony/test/stress/classloader/share/FieldsLmtClasses/testFieldsLmt_C1/testF9999 I
    return
.end method
.method public getFirst()I
    .limit stack 2
    .limit locals 2
    aload_0
    getfield  org/apache/harmony/test/stress/classloader/share/FieldsLmtClasses/testFieldsLmt_C1/testF0 I
    ireturn
.end method
.method public getLast()I
    .limit stack 2
    .limit locals 2
    aload_0
    getfield  org/apache/harmony/test/stress/classloader/share/FieldsLmtClasses/testFieldsLmt_C1/testF9999 I
    ireturn
.end method
