;    Copyright 2005-2006 The Apache Software Foundation or its licensors, as applicable
;
;    Licensed under the Apache License, Version 2.0 (the "License");
;    you may not use this file except in compliance with the License.
;    You may obtain a copy of the License at
;
;       http://www.apache.org/licenses/LICENSE-2.0
;
;    Unless required by applicable law or agreed to in writing, software
;    distributed under the License is distributed on an "AS IS" BASIS,
;    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
;
;    See the License for the specific language governing permissions and
;    limitations under the License.

;
; Author: Ilia A. Leviev
; Version: $Revision: 1.2 $
;

.class public org/apache/harmony/vts/test/vm/jvms/classFile/finally/finally04/finally0401/finally0401
.super java/lang/Object


;
; standard initializer
.method public <init>()V
   aload_0
   invokespecial java/lang/Object/<init>()V
   return
.end method

;
; testW method

.method public  testw()V
   .limit stack 2
   .limit locals 3  

   .catch org/apache/harmony/vts/test/vm/jvms/classFile/finally/finally04/finally0401/TestException from L1 to L2 using L4  

   L1:
        aload_0				
   	  invokevirtual org/apache/harmony/vts/test/vm/jvms/classFile/finally/finally04/finally0401/finally0401/testTry()V 		
       
   L2:
    	 jsr J1				
    	 return				
  L4:    
      astore_1			
   	jsr J1				
   	aload_1			
  	athrow				
  J1:
      astore_2			
   	aload_0				
   	invokevirtual org/apache/harmony/vts/test/vm/jvms/classFile/finally/finally04/finally0401/finally0401/testF()V  	
      ret 2		


  
.end method

; testTry method
.method public  testTry()V

 .limit stack 2
 .limit locals 1  
   new org/apache/harmony/vts/test/vm/jvms/classFile/finally/finally04/finally0401/TestException
   dup   
   invokespecial org/apache/harmony/vts/test/vm/jvms/classFile/finally/finally04/finally0401/TestException/<init>()V
   athrow    
.end method


; testF method
.method public  testF()V

 .limit stack 2
 .limit locals 1  
   new org/apache/harmony/vts/test/vm/jvms/classFile/finally/finally04/finally0401/TestExceptionF
   dup   
   invokespecial org/apache/harmony/vts/test/vm/jvms/classFile/finally/finally04/finally0401/TestExceptionF/<init>()V
   athrow    

.end method

