;    Copyright 2005-2006 The Apache Software Foundation or its licensors, as applicable
;
;    Licensed under the Apache License, Version 2.0 (the "License");
;    you may not use this file except in compliance with the License.
;    You may obtain a copy of the License at
;
;       http://www.apache.org/licenses/LICENSE-2.0
;
;    Unless required by applicable law or agreed to in writing, software
;    distributed under the License is distributed on an "AS IS" BASIS,
;    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
;
;    See the License for the specific language governing permissions and
;    limitations under the License.

;
; Author: Alexander V. Esin
; Version: $Revision: 1.1 $
;
.bytecode 49.0
.class public org/apache/harmony/vts/test/vm/jvms/classFile/attributes/annotation/runtimeVisibleParameterAnnotations/methodinfo01/annotation01p
.super java/lang/Object

.method public <init>()V
   aload_0
   invokespecial java/lang/Object/<init>()V
   return
.end method
; annotated method
.method public testMethod(I)V
  .limit stack 1
  .limit locals 2
  .annotation visibleparam 1 Lorg/apache/harmony/vts/test/vm/jvms/classFile/attributes/annotation/runtimeVisibleParameterAnnotations/methodinfo01/annotation01;
  .end annotation
   return
.end method
