;    Copyright 2005-2006 The Apache Software Foundation or its licensors, as applicable
;
;    Licensed under the Apache License, Version 2.0 (the "License");
;    you may not use this file except in compliance with the License.
;    You may obtain a copy of the License at
;
;       http://www.apache.org/licenses/LICENSE-2.0
;
;    Unless required by applicable law or agreed to in writing, software
;    distributed under the License is distributed on an "AS IS" BASIS,
;    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
;
;    See the License for the specific language governing permissions and
;    limitations under the License.

;
; Author: Mikhail Bolotov
; Version: $Revision: 1.2 $
;

.class public org/apache/harmony/vts/test/vm/jvms/classLLI/loading/loading08/loading08pClassLoader
.super java/lang/ClassLoader

.field public result I

.method public <init>()V
.limit stack 2
.limit locals 1
	aload_0
	invokespecial java/lang/ClassLoader/<init>()V

	aload_0
	bipush 0
	putfield org/apache/harmony/vts/test/vm/jvms/classLLI/loading/loading08/loading08pClassLoader/result I

	return
.end method

.method public loadClass(Ljava/lang/String;)Ljava/lang/Class;
.throws java/lang/ClassNotFoundException
.limit stack 3
.limit locals 2
	aload_1
	ldc "org.apache.harmony.vts.test.vm.jvms.classLLI.loading.loading08.loading08pClassTest"
	invokevirtual java/lang/String/equals(Ljava/lang/Object;)Z
	ifeq lClassTest
	aload_0
	dup
	getfield org/apache/harmony/vts/test/vm/jvms/classLLI/loading/loading08/loading08pClassLoader/result I
	iconst_1
	iadd
	putfield org/apache/harmony/vts/test/vm/jvms/classLLI/loading/loading08/loading08pClassLoader/result I

lClassTest:
	aload_0
	aload_1
	invokespecial java/lang/ClassLoader/loadClass(Ljava/lang/String;)Ljava/lang/Class;
	areturn
.end method

