;    Copyright 2005-2006 The Apache Software Foundation or its licensors, as applicable
;
;    Licensed under the Apache License, Version 2.0 (the "License");
;    you may not use this file except in compliance with the License.
;    You may obtain a copy of the License at
;
;       http://www.apache.org/licenses/LICENSE-2.0
;
;    Unless required by applicable law or agreed to in writing, software
;    distributed under the License is distributed on an "AS IS" BASIS,
;    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
;
;    See the License for the specific language governing permissions and
;    limitations under the License.

;
; Author: Alexander D. Shipilov
; Version: $Revision: 1.1.1.1 $
;

.class public org/apache/harmony/vts/test/vm/jvms/instructions/invokeReturn/invokespecial/invokespecial06/invokespecial0601/invokespecial0601pSuper
.super java/lang/Object

;
; standard initializer
.method public <init>()V
   aload_0
   invokespecial java/lang/Object/<init>()V
   return
.end method

;
; virtualTest method
.method protected virtualTest(Ljava/lang/String;IDJ)I
   .limit stack 4
   .limit locals 7

; load String from local 1 and checking it (must be == "Hello!")
   aload_1
   ldc "Hello!"
   if_acmpne Fail

; load int from local 2 and checking it (must be == 3)
   iload_2
   iconst_3
   if_icmpne Fail

; load double from local 3 and 4 and checking it (must be == "1.0")
   dload_3
   dconst_1
   dcmpg
   ifne Fail

; load int from local 5 and 6 and checking it (must be == "1")
    lload 5
    lconst_1
    lcmp
    ifne Fail

   sipush 104 ; push 104
   ireturn ; return 104

; local_1!="Hello!" or local_2!=3 or local_(3<< + 4)!=1.0 or local_(5<< + 6)!=1
Fail:
   sipush 105
   ireturn

.end method
