;    Copyright 2005-2006 The Apache Software Foundation or its licensors, as applicable
;
;    Licensed under the Apache License, Version 2.0 (the "License");
;    you may not use this file except in compliance with the License.
;    You may obtain a copy of the License at
;
;       http://www.apache.org/licenses/LICENSE-2.0
;
;    Unless required by applicable law or agreed to in writing, software
;    distributed under the License is distributed on an "AS IS" BASIS,
;    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
;
;    See the License for the specific language governing permissions and
;    limitations under the License.

;
; Author: Mikhail Bolotov
; Version: $Revision: 1.2 $
;

.class public org/apache/harmony/vts/test/vm/jvms/classLLI/loading/loading07/loading07pClassLoader
.super java/lang/ClassLoader



.method public <init>()V
.limit stack 2
.limit locals 1
	aload_0
	invokespecial java/lang/ClassLoader/<init>()V
	return
.end method

.method public loadClass(Ljava/lang/String;)Ljava/lang/Class;
.throws java/lang/ClassNotFoundException
.limit stack 5
.limit locals 3
;
;	delegate the loading to another class loader:
;	new loadingClassLoader().loadString(local1)
;
	new org/apache/harmony/vts/test/vm/jvms/classLLI/loading/share/loadingClassLoader
	dup
	invokespecial org/apache/harmony/vts/test/vm/jvms/classLLI/loading/share/loadingClassLoader/<init>()V
	aload_1
	invokevirtual org/apache/harmony/vts/test/vm/jvms/classLLI/loading/share/loadingClassLoader/loadClass(Ljava/lang/String;)Ljava/lang/Class;
	areturn
.end method

