;    Copyright 2005-2006 The Apache Software Foundation or its licensors, as applicable
;
;    Licensed under the Apache License, Version 2.0 (the "License");
;    you may not use this file except in compliance with the License.
;    You may obtain a copy of the License at
;
;       http://www.apache.org/licenses/LICENSE-2.0
;
;    Unless required by applicable law or agreed to in writing, software
;    distributed under the License is distributed on an "AS IS" BASIS,
;    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
;
;    See the License for the specific language governing permissions and
;    limitations under the License.

;
; Author: Alexander V. Esin
; Version: $Revision: 1.1 $
;

.class public org/apache/harmony/vts/test/vm/jvms/instructions/invokeReturn/invokevirtual/invokevirtual23/invokevirtual2301/invokevirtual2301pSuper
.super java/lang/Object

.method public <init>()V
   aload_0
   invokespecial java/lang/Object/<init>()V
   return
.end method

; virtualTest method, if it is invoked instead of virtualTest method
; of derived class it returns 105 (which means failure)
.method public virtualTest()I
   .limit stack 1
   .limit locals 1
   sipush 105
   ireturn
.end method

;
; auxiliaryMethod invokes 'its' virtualTest method, 
; but virtualTest of derived class should be invoked
.method public auxiliaryMethod()I
.limit stack 1
.limit locals 1
   aload_0 ; push this
   invokevirtual org/apache/harmony/vts/test/vm/jvms/instructions/invokeReturn/invokevirtual/invokevirtual23/invokevirtual2301/invokevirtual2301pSuper/virtualTest()I
   ireturn
.end method