;    Copyright 2005-2006 The Apache Software Foundation or its licensors, as applicable
;
;    Licensed under the Apache License, Version 2.0 (the "License");
;    you may not use this file except in compliance with the License.
;    You may obtain a copy of the License at
;
;       http://www.apache.org/licenses/LICENSE-2.0
;
;    Unless required by applicable law or agreed to in writing, software
;    distributed under the License is distributed on an "AS IS" BASIS,
;    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
;
;    See the License for the specific language governing permissions and
;    limitations under the License.

;
; Author: Alexander D. Shipilov
; Version: $Revision: 1.1.1.1 $
;

.class public org/apache/harmony/vts/test/vm/jvms/classLLI/linking/linking04/linking0401/linking0401nTest
.super java/lang/Object
.implements org/apache/harmony/vts/test/vm/jvms/classLLI/linking/linking04/linking0401/linking0401nInterface

;
; initializer
.method public <init>()V
   aload_0
   invokespecial java/lang/Object/<init>()V
   return
.end method

;
; test method
.method public static testMethod()I
  .limit stack 2
  .limit locals 2

  new org/apache/harmony/vts/test/vm/jvms/classLLI/linking/linking04/linking0401/linking0401nTest
  dup
  invokespecial org/apache/harmony/vts/test/vm/jvms/classLLI/linking/linking04/linking0401/linking0401nTest/<init>()V
  invokeinterface org/apache/harmony/vts/test/vm/jvms/classLLI/linking/linking04/linking0401/linking0401nInterface/testMethod()I 1
  sipush 105
  ireturn

.end method
