;    Copyright 2005-2006 The Apache Software Foundation or its licensors, as applicable
;
;    Licensed under the Apache License, Version 2.0 (the "License");
;    you may not use this file except in compliance with the License.
;    You may obtain a copy of the License at
;
;       http://www.apache.org/licenses/LICENSE-2.0
;
;    Unless required by applicable law or agreed to in writing, software
;    distributed under the License is distributed on an "AS IS" BASIS,
;    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
;
;    See the License for the specific language governing permissions and
;    limitations under the License.

;
; Author: Alexander D. Shipilov
; Version: $Revision: 1.2 $
;

.interface public org/apache/harmony/vts/test/vm/jvms/classLLI/initialization/initialization05/initialization0502/initialization0502pInterface
.super java/lang/Object
.field static final public testField I=1

;
; static initializer
.method public static <clinit>()V
   .limit stack 4
   .limit locals 2
   
   getstatic org/apache/harmony/vts/test/vm/jvms/classLLI/initialization/initialization05/initialization0502/initialization0502p/synchField I
   sipush 2
   if_icmpeq lab
; if not equal this means that second thread try to initialize this class in the same time as first thread.
   sipush 105
   putstatic org/apache/harmony/vts/test/vm/jvms/classLLI/initialization/initialization05/initialization0502/initialization0502p/testField I
   goto lab2

lab:
   sipush 104
   putstatic org/apache/harmony/vts/test/vm/jvms/classLLI/initialization/initialization05/initialization0502/initialization0502p/testField I

lab2:
   sipush 1
   putstatic org/apache/harmony/vts/test/vm/jvms/classLLI/initialization/initialization05/initialization0502/initialization0502p/synchField I

; wait 8 seconds. During this time second thread should try to invoke 
; this method. If this is not synchronized procedure, test fails.
   sipush 8000
   i2l
   invokestatic java/lang/Thread/sleep(J)V

   return
.end method
