;  Licensed to the Apache Software Foundation (ASF) under one or more
;  contributor license agreements.  See the NOTICE file distributed with
;  this work for additional information regarding copyright ownership.
;  The ASF licenses this file to You under the Apache License, Version 2.0
;  (the "License"); you may not use this file except in compliance with
;  the License.  You may obtain a copy of the License at
;
;     http://www.apache.org/licenses/LICENSE-2.0
;
;  Unless required by applicable law or agreed to in writing, software
;  distributed under the License is distributed on an "AS IS" BASIS,
;  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
;  See the License for the specific language governing permissions and
;  limitations under the License.
;
;
;

.class public org/apache/harmony/test/func/vm/verifier/field/Test04/Test04Ver
.super java/lang/Object
.field public testFieldB Lorg/apache/harmony/test/func/vm/verifier/field/Test04/Test04B;

;
; standard initializer
.method public <init>()V
   aload_0
   invokespecial java/lang/Object/<init>()V
   return
.end method

;
; test method
.method public test()V
   .limit stack 3
   .limit locals 2

   aload_0
   iconst_1
   ifeq lab1
   new org/apache/harmony/test/func/vm/verifier/field/Test04/Test04C
   dup
   invokespecial org/apache/harmony/test/func/vm/verifier/field/Test04/Test04C/<init>()V
   goto lab2

lab1:
   new org/apache/harmony/test/func/vm/verifier/field/Test04/Test04E
   dup
   invokespecial org/apache/harmony/test/func/vm/verifier/field/Test04/Test04E/<init>()V

lab2:
   putfield org/apache/harmony/test/func/vm/verifier/field/Test04/Test04Ver/testFieldB Lorg/apache/harmony/test/func/vm/verifier/field/Test04/Test04B;

   return
.end method
