;    Copyright 2005-2006 The Apache Software Foundation or its licensors, as applicable
;
;    Licensed under the Apache License, Version 2.0 (the "License");
;    you may not use this file except in compliance with the License.
;    You may obtain a copy of the License at
;
;       http://www.apache.org/licenses/LICENSE-2.0
;
;    Unless required by applicable law or agreed to in writing, software
;    distributed under the License is distributed on an "AS IS" BASIS,
;    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
;
;    See the License for the specific language governing permissions and
;    limitations under the License.

	;
; Author: Alexander D. Shipilov
; Version: $Revision: 1.1.1.1 $
;

.class public org/apache/harmony/vts/test/vm/jvms/instructions/invokeReturn/invokevirtual/invokevirtual04/invokevirtual0401/invokevirtual0401pSuper
.super java/lang/Object

;
; standard initializer
.method public <init>()V
   aload_0
   invokespecial java/lang/Object/<init>()V
   return
.end method

;
; virtualTest method
.method public virtualTest(Ljava/lang/String;I)I
   .limit stack 2
   .limit locals 3

; load String from local 1 and checking it (must be == "Hello!")
   aload_1
   ldc "Hello!"
   if_acmpne Fail

; load int from local 2 and checking it (must be == 3)
   iload_2
   iconst_3
   if_icmpne Fail

   sipush 104
   ireturn

; local_0!="Hello!" or local_1!=2
Fail:
   sipush 105
   ireturn

   sipush 104 ; push 104
   ireturn ; return 104

.end method
