/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */    
/*
 * THE FILE HAS BEEN AUTOGENERATED BY THE IJH TOOL.
 * Please be aware that all changes made to this file manually
 * will be overwritten by the tool if it runs again.
 */

#include <jni.h>


/* Header for class org.apache.harmony.test.stress.jni.arguments.ArgumentsTest */

#ifndef _ORG_APACHE_HARMONY_TEST_STRESS_JNI_ARGUMENTS_ARGUMENTSTEST_H
#define _ORG_APACHE_HARMONY_TEST_STRESS_JNI_ARGUMENTS_ARGUMENTSTEST_H

#ifdef __cplusplus
extern "C" {
#endif


/* Static final fields */

#undef org_apache_harmony_test_stress_jni_arguments_ArgumentsTest_TM_ERROR_NONE
#define org_apache_harmony_test_stress_jni_arguments_ArgumentsTest_TM_ERROR_NONE 0L

#undef org_apache_harmony_test_stress_jni_arguments_ArgumentsTest_TM_ERROR_INTERRUPT
#define org_apache_harmony_test_stress_jni_arguments_ArgumentsTest_TM_ERROR_INTERRUPT 52L

#undef org_apache_harmony_test_stress_jni_arguments_ArgumentsTest_TM_ERROR_ILLEGAL_STATE
#define org_apache_harmony_test_stress_jni_arguments_ArgumentsTest_TM_ERROR_ILLEGAL_STATE 118L


/* Native methods */

/*
 * Method: org.apache.harmony.test.stress.jni.arguments.ArgumentsTest.nativeMethod(CLjava/lang/Object;ZDIDJZZILjava/lang/Object;SLjava/lang/Object;FCLjava/lang/Object;JDZLjava/lang/Object;DFCZFFZIIDFIIDIIJIZFLjava/lang/Object;IDDDDLjava/lang/Object;Ljava/lang/Object;SFJDZFCLjava/lang/Object;FJSFJCZFCIDFLjava/lang/Object;CSDJLjava/lang/Object;DDFFCZLjava/lang/Object;JIFJIFSDCCIDFCJJZCZJDIDDJCSLjava/lang/Object;SLjava/lang/Object;IFLjava/lang/Object;FFZLjava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;DSLjava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;CJSZSZLjava/lang/Object;Ljava/lang/Object;DSSZJIFJDCFLjava/lang/Object;JSIILjava/lang/Object;ZLjava/lang/Object;ICJLjava/lang/Object;CZF)Z
 */
JNIEXPORT jboolean JNICALL
Java_org_apache_harmony_test_stress_jni_arguments_ArgumentsTest_nativeMethod(JNIEnv *, jobject, 
    jchar, jobject, jboolean, jdouble, jint, jdouble, jlong, jboolean, jboolean, jint, jobject, jshort, jobject, jfloat, jchar, jobject, jlong, jdouble, jboolean, jobject, jdouble, jfloat, jchar, jboolean, jfloat, jfloat, jboolean, jint, jint, jdouble, jfloat, jint, jint, jdouble, jint, jint, jlong, jint, jboolean, jfloat, jobject, jint, jdouble, jdouble, jdouble, jdouble, jobject, jobject, jshort, jfloat, jlong, jdouble, jboolean, jfloat, jchar, jobject, jfloat, jlong, jshort, jfloat, jlong, jchar, jboolean, jfloat, jchar, jint, jdouble, jfloat, jobject, jchar, jshort, jdouble, jlong, jobject, jdouble, jdouble, jfloat, jfloat, jchar, jboolean, jobject, jlong, jint, jfloat, jlong, jint, jfloat, jshort, jdouble, jchar, jchar, jint, jdouble, jfloat, jchar, jlong, jlong, jboolean, jchar, jboolean, jlong, jdouble, jint, jdouble, jdouble, jlong, jchar, jshort, jobject, jshort, jobject, jint, jfloat, jobject, jfloat, jfloat, jboolean, jobject, jobject, jobject, jdouble, jshort, jobject, jobject, jobject, jchar, jlong, jshort, jboolean, jshort, jboolean, jobject, jobject, jdouble, jshort, jshort, jboolean, jlong, jint, jfloat, jlong, jdouble, jchar, jfloat, jobject, jlong, jshort, jint, jint, jobject, jboolean, jobject, jint, jchar, jlong, jobject, jchar, jboolean, jfloat);


#ifdef __cplusplus
}
#endif

#endif /* _ORG_APACHE_HARMONY_TEST_STRESS_JNI_ARGUMENTS_ARGUMENTSTEST_H */

