;    Copyright 2005-2006 The Apache Software Foundation or its licensors, as applicable
;
;    Licensed under the Apache License, Version 2.0 (the "License");
;    you may not use this file except in compliance with the License.
;    You may obtain a copy of the License at
;
;       http://www.apache.org/licenses/LICENSE-2.0
;
;    Unless required by applicable law or agreed to in writing, software
;    distributed under the License is distributed on an "AS IS" BASIS,
;    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
;
;    See the License for the specific language governing permissions and
;    limitations under the License.

;
; Author: Alexander D. Shipilov
; Version: $Revision: 1.2 $
;

.class public org/apache/harmony/vts/test/vm/jvms/instructions/invokeReturn/return/return02/return0201/return0201pFirst
.super java/lang/Thread
.field public lockerField [I

;
; initializer
.method public <init>([I)V
   .limit stack 2
   .limit locals 3

   aload_0
   invokespecial java/lang/Thread/<init>()V

; store locker array in this.lockerField field
   aload_0
   aload_1
   putfield org/apache/harmony/vts/test/vm/jvms/instructions/invokeReturn/return/return02/return0201/return0201pFirst/lockerField [I

   return
.end method

;
; run method
.method public synchronized run()V
   .limit stack 1
   .limit locals 2
   
; get locker object from lockerField field and store it in local variable 1
   aload_0
   getfield org/apache/harmony/vts/test/vm/jvms/instructions/invokeReturn/return/return02/return0201/return0201pFirst/lockerField [I
   astore_1

; get a lock to locker object
   aload_1
   monitorenter
   aload_1
   monitorexit

; return must unlock locker object
   return

.end method
