;  Licensed to the Apache Software Foundation (ASF) under one or more
;  contributor license agreements.  See the NOTICE file distributed with
;  this work for additional information regarding copyright ownership.
;  The ASF licenses this file to You under the Apache License, Version 2.0
;  (the "License"); you may not use this file except in compliance with
;  the License.  You may obtain a copy of the License at
;
;     http://www.apache.org/licenses/LICENSE-2.0
;
;  Unless required by applicable law or agreed to in writing, software
;  distributed under the License is distributed on an "AS IS" BASIS,
;  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
;  See the License for the specific language governing permissions and
;  limitations under the License.
;
;
;

.class public org/apache/harmony/test/func/jit/HLO/uce/unreach_if_cmpne/UnreachIF_CMPNE
.super java/lang/Object

;
; standard initializer
.method public <init>()V
   aload_0
   invokenonvirtual java/lang/Object/<init>()V
   return
.end method

;
; test method
.method public test()I
   .limit stack 4
   .limit locals 20 
L1:   
   iconst_1
   istore_1

   iconst_2
   iconst_3
   if_icmpne L0     ;unreachable code is going right after this line (till lablel L0)
   
   ldc 3           
   iload_1         
   iadd
   istore_1
   goto L2
L0:
   iload_1
   ireturn
L2:    
   wide
   sipush 0
   ireturn
.end method

