;    Copyright 2005-2006 The Apache Software Foundation or its licensors, as applicable
;
;    Licensed under the Apache License, Version 2.0 (the "License");
;    you may not use this file except in compliance with the License.
;    You may obtain a copy of the License at
;
;       http://www.apache.org/licenses/LICENSE-2.0
;
;    Unless required by applicable law or agreed to in writing, software
;    distributed under the License is distributed on an "AS IS" BASIS,
;    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
;
;    See the License for the specific language governing permissions and
;    limitations under the License.

;
; Author: Alexander D. Shipilov
; Version: $Revision: 1.4 $
;

.class public org/apache/harmony/vts/test/vm/jvms/classLLI/initialization/initialization06/initialization0601/initialization0601pThread2
.super java/lang/Thread

;
; initializer
.method public <init>()V
   aload_0
   invokespecial java/lang/Thread/<init>()V
   return
.end method

;
; run method
.method public run()V
   .limit stack 3
   .limit locals 4

  .catch java/lang/NoClassDefFoundError from lab1 to lab2 using lab3
lab1:
; invoke static method. Thereby initiate static initialization. Should throw java/lang/NoClassDefFoundError.
   invokestatic org/apache/harmony/vts/test/vm/jvms/classLLI/initialization/initialization06/initialization0601/initialization0601pTest/testMethod()V
   sipush 105
   putstatic org/apache/harmony/vts/test/vm/jvms/classLLI/initialization/initialization06/initialization0601/initialization0601p/testField I
lab2:
   return

lab3:
; second thread pass
   return

.end method
