;    Copyright 2005-2006 The Apache Software Foundation or its licensors, as applicable
;
;    Licensed under the Apache License, Version 2.0 (the "License");
;    you may not use this file except in compliance with the License.
;    You may obtain a copy of the License at
;
;       http://www.apache.org/licenses/LICENSE-2.0
;
;    Unless required by applicable law or agreed to in writing, software
;    distributed under the License is distributed on an "AS IS" BASIS,
;    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
;
;    See the License for the specific language governing permissions and
;    limitations under the License.

;
; Author: Alexander D. Shipilov
; Version: $Revision: 1.3 $
;

.class public org/apache/harmony/vts/test/vm/jvms/classLLI/initialization/initialization06/initialization0601/initialization0601pTest
.super java/lang/Thread
.field static public testField I=2

;
; initializer
.method public <init>()V
   aload_0
   invokespecial java/lang/Thread/<init>()V
   return
.end method

;
; static initializer
.method public static <clinit>()V
   .limit stack 4
   .limit locals 2

   sipush 104
   putstatic org/apache/harmony/vts/test/vm/jvms/classLLI/initialization/initialization06/initialization0601/initialization0601p/testField I
   
; wait 8 seconds. During this time second thread should try to invoke 
; this method. If this is not synchronized procedure, test fails.
   sipush 1000
   i2l
   invokestatic java/lang/Thread/sleep(J)V

   new java/lang/Exception
   dup   
   invokespecial java/lang/Exception/<init>()V
   athrow

   return
.end method

; test method
.method public static testMethod()V
	.limit stack 1
	.limit locals 1
	
   return
.end method
