;  Licensed to the Apache Software Foundation (ASF) under one or more
;  contributor license agreements.  See the NOTICE file distributed with
;  this work for additional information regarding copyright ownership.
;  The ASF licenses this file to You under the Apache License, Version 2.0
;  (the "License"); you may not use this file except in compliance with
;  the License.  You may obtain a copy of the License at
;
;     http://www.apache.org/licenses/LICENSE-2.0
;
;  Unless required by applicable law or agreed to in writing, software
;  distributed under the License is distributed on an "AS IS" BASIS,
;  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
;  See the License for the specific language governing permissions and
;  limitations under the License.
;
;
;

.class public org/apache/harmony/test/func/jit/HLO/memopt/memoptint2/MemoptInt2
.super java/lang/Object
.field public f I
;
; standard initializer
.method public <init>()V
   .limit stack 2
   .limit locals 2
   aload_0
   invokenonvirtual java/lang/Object/<init>()V
   aload_0
   iconst_1
   putfield org/apache/harmony/test/func/jit/HLO/memopt/memoptint2/MemoptInt2/f I
   return
.end method

;
; test method
.method public static test()I
   .limit stack 5
   .limit locals 5 
   new org/apache/harmony/test/func/jit/HLO/memopt/memoptint2/MemoptInt2
   dup
   invokespecial org/apache/harmony/test/func/jit/HLO/memopt/memoptint2/MemoptInt2/<init>()V

   astore_0
   aload_0
   getfield  org/apache/harmony/test/func/jit/HLO/memopt/memoptint2/MemoptInt2/f I
   istore_1
   iconst_0
   istore_2
   iconst_1 ;boolean value
   istore_3
   iload_3
   ifeq L0
   aload_0
   getfield  org/apache/harmony/test/func/jit/HLO/memopt/memoptint2/MemoptInt2/f I
   istore_2
L0:
   iload_1
   iload_2
   if_icmpeq L1      
   iconst_0
   ireturn
L1:
   iconst_1
   ireturn
.end method
