;  Licensed to the Apache Software Foundation (ASF) under one or more
;  contributor license agreements.  See the NOTICE file distributed with
;  this work for additional information regarding copyright ownership.
;  The ASF licenses this file to You under the Apache License, Version 2.0
;  (the "License"); you may not use this file except in compliance with
;  the License.  You may obtain a copy of the License at
;
;     http://www.apache.org/licenses/LICENSE-2.0
;
;  Unless required by applicable law or agreed to in writing, software
;  distributed under the License is distributed on an "AS IS" BASIS,
;  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
;  See the License for the specific language governing permissions and
;  limitations under the License.
;
;
;

.class public org/apache/harmony/test/func/jit/HLO/dce/deadrecursive2/DeadRecursive2
.super java/lang/Object

;
; standard initializer
.method public <init>()V
   aload_0
   invokenonvirtual java/lang/Object/<init>()V
   return
.end method

;
; recursive method
.method private test(I)I
   .limit stack 4
   .limit locals 10 
   iload_1
   ;dead code
   dup
   dup
   iadd
   istore_3
   ;end dead code
   ifne L0
   iconst_1
   ireturn
L0:
   aload_0
   iload_1
   iconst_1
   isub
   invokevirtual org/apache/harmony/test/func/jit/HLO/dce/deadrecursive2/DeadRecursive2/test(I)I
   iload_1
   imul
   ireturn
.end method

;
; test method
.method public test()I
   .limit stack 4
   .limit locals 4 

   aload_0
   bipush 10
   dup
   istore_2  ;dead veriable to store return function value
   invokevirtual  org/apache/harmony/test/func/jit/HLO/dce/deadrecursive2/DeadRecursive2/test(I)I
   istore_1  
   iload_1
   ldc 3628800
   isub
   ifne L1
   wide
   sipush 1
   ireturn
L1:
   wide
   sipush 0
   ireturn
.end method
